name: "✨ Feature Request"
description: "Suggest a new feature or enhancement."
type: Feature
body:
  - type: checkboxes
    id: guidelines
    attributes:
      label: "Guidelines"
      description: |
        Please search for similar requests to avoid duplicates. If you find a similar one, comment there instead.
        [Search existing requests](https://github.com/mollyim/mollyim-android/issues?q=is%3Aissue+type%3AFeature).
      options:
        - label: "Yes, I have searched the existing requests"
          required: true
  - type: textarea
    id: description-of-feature
    attributes:
      label: "Feature Description"
      description: "Describe the feature you'd like to see added."
    validations:
      required: true
